server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  # model
  type-aliases-package: org.spring.springboot.domain
  # xml file
  mapper-locations: classpath:mapper/*.xml
