server:
  port: 8888

spring:
  datasource:
    # 主数据库配置
    primary:
      url: jdbc:mysql://142.171.9.183:6060/movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    # 从数据库配置
    secondary:
      url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456




mybatis:
  # model
  type-aliases-package: org.spring.springboot.domain
  # xml file
  mapper-locations: classpath:mapper/*.xml
